spring:
  application:
    name: team10-poomasi
  config:
    import: optional:application-secret.yml
  token:
    storage: #리프레시 토큰 저장소
      type: jpa
      #type: redis
    blacklist: #블랙리스트 저장소
      type: jpa
      #type: redis

