spring:
    application:
        name: team10-poomasi
logging:
    level:
        org:
            springframework:
                security : TRACE
                web: DEBUG

#spring.application.name=team10-poomasi