jwt:
  secret: "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="
  access-token-expiration-time: 3600000 # 1시간
  refresh-token-expiration-time: 604800000  # 7일

spring:
  application:
    name: poomasi
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        hbm2ddl:
          jdbc_metadata_extraction_strategy: individually
  datasource:
    url: jdbc:mysql://localhost:3306/poomasi
    username: root
    password: 12345678
  data:
    redis:
      port: 6380
      host: localhost

logging:
  level:
    org:
      springframework:
        web: DEBUG